### ISSUE TITLE
Issue with return promise

### ISSUE THREAD

**Issue by spielcrypto** [pyrite-framework/pyrite-server#7]
When I return some object without promise the curl call shows me the respond correctly but when I return a promise it shows me a empty object

```
@Route("/feeds")
class feeds {
  @Get("/facebook/:id")
  getFacebookEvents(@Params('id') id) {
    const options: Object = {
      version: "v2.10",
      appId: '107628596626055',
      appSecret: '5c03ed2a61e1d6567bc2fb5b09706d12'
    }
    const facebook = new FacebookApi(options);
    return facebook.getAccessToken(options).then(data => {
      return facebook.getEntriesGroup(`${id}/feed`, data.access_token).then(response => {
        return response.data;
      });
    });
  }
}
```

If I do a console.log of response.data inside of the promise facebook.getEntriesGroup and I get the result which I expected. Maybe it is something that I'm doing wrong

this is the CURL:
`curl -X GET http://localhost:8000/feeds/facebook/502044263177792`

**Comment by fagarbal** [comment]
released.
